spring.application.name=smartledger

spring.datasource.url=jdbc:mysql://localhost:3306/smartledger
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

gemini.api.key=${GEMINI_API_KEY}

jwt.secret=U21hcnRMZWRnZXJBdXRoZW50aWNhdGlvbktleUZvclN1cGVyU2VjdXJlVjE
jwt.expiration=86400000
